sudo: required
services:
    - docker

before_install:
    - docker build -t raunakjodhawat/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true raunakjodhawat/react-test npm test -- --coverage

after_success:
    - docker build -t raunakjodhawat/multi-client ./client
    - docker build -t raunakjodhawat/multi-worker ./worker
    - docker build -t raunakjodhawat/multi-server ./server
    - docker build -t raunakjodhawat/multi-nginx ./nginx
    # docker log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push image to docker hub
    - docker push raunakjodhawat/multi-client
    - docker push raunakjodhawat/multi-worker
    - docker push raunakjodhawat/multi-server
    - docker push raunakjodhawat/multi-nginx

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker-2"
    env: "MultiDocker2-env"
    bucker_name: "elasticbeanstalk-us-east-2-681334850105"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"