version: "3"
services: 
    postgres:
        image: 'postgres:latest'
        environment:
            POSTGRES_DB: "db"
            POSTGRES_HOST_AUTH_METHOD: "trust"
    redis:
        image: 'redis:latest'
    api:
        depends_on: 
            - postgres
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGPASS=postgres_password
            - PGHOST=postgres
            - PGPORT=5432
            - PGDATABASE=postgres
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
        stdin_open: true
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    nginx:
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        volumes:
            - ./nginx:/app
        ports:
            - "3050:80"
        restart: always
        